<nav>
    <menu>
        <ul>
            <li>
                <span class="lisTitle"><a href="/MVC/">Accueil</a></span>
            </li>
            <li>
                <span class="lisTitle">Utilisateurs</span>
                <ul>
                    <li><a href="/MVC/User/add">Ajouter un utilisateur</a></li>
                    <li><a href="/MVC/User/viewuser">Administrer les utilisateurs</a></li>
                    <!--<li>Voir un utilisateur</li>-->
                </ul>
            </li>
            <li>
                <span class="lisTitle">Catégories</span>
                <ul>
                    <li><a href="/MVC/Category/viewall">Gérer les Catégories</a></li>
                    <li><a href="/MVC/Project/viewproject">Gérer les Projets</a></li>
                    <li><a href="/MVC/Phase/viewphase">Gérer les Phases</a></li>
                </ul>
            </li>
            <li>
                <span class="lisTitle">Taches</span>
                <ul>
                    <li><a href="/MVC/Task/add">Ajouter une tâche</a></li>
                    <li><a href="/MVC/Task/viewtasks">Administrer les tâche</a></li>
                </ul>
            </li>
            <li>
                <span class="lisTitle"><a href="/MVC/User/disconnect">Déconnecter</a></span>
            </li>
        </ul>
    </menu>
</nav>
